_format_version: "3.0"

# Services - Backend microservices
services:
  - name: user-service
    url: http://user-service:8000
    connect_timeout: 5000
    read_timeout: 60000
    write_timeout: 60000
    
  - name: organization-service
    url: http://organization-service:8000
    connect_timeout: 5000
    read_timeout: 60000
    write_timeout: 60000
    
  - name: leave-service
    url: http://leave-service:8000
    connect_timeout: 5000
    read_timeout: 60000
    write_timeout: 60000
    
  - name: attendance-service
    url: http://attendance-service:8000
    connect_timeout: 5000
    read_timeout: 60000
    write_timeout: 60000
    
  - name: reimbursement-service
    url: http://reimbursement-service:8000
    connect_timeout: 5000
    read_timeout: 60000
    write_timeout: 60000
    
  - name: project-service
    url: http://project-service:8000
    connect_timeout: 5000
    read_timeout: 60000
    write_timeout: 60000
    
  - name: payroll-service
    url: http://payroll-service:8000
    connect_timeout: 5000
    read_timeout: 60000
    write_timeout: 60000
    
  - name: taxation-service
    url: http://taxation-service:8000
    connect_timeout: 5000
    read_timeout: 60000
    write_timeout: 60000
    
  - name: reporting-service
    url: http://reporting-service:8000
    connect_timeout: 5000
    read_timeout: 60000
    write_timeout: 60000

# Routes - API endpoint routing
routes:
  # User Service Routes
  - name: user-auth-routes
    service: user-service
    paths:
      - /api/v2/auth
    methods:
      - GET
      - POST
      - PUT
      - DELETE
    strip_path: false
    
  - name: user-routes
    service: user-service
    paths:
      - /api/v2/users
    methods:
      - GET
      - POST
      - PUT
      - DELETE
    strip_path: false
    
  # Organization Service Routes
  - name: organization-routes
    service: organization-service
    paths:
      - /api/v2/organizations
      - /api/v2/organisations
    methods:
      - GET
      - POST
      - PUT
      - DELETE
    strip_path: false
    
  # Leave Service Routes
  - name: leave-routes
    service: leave-service
    paths:
      - /api/v2/leaves
      - /api/v2/employee-leave
      - /api/v2/company-leaves
      - /api/v2/public-holidays
    methods:
      - GET
      - POST
      - PUT
      - DELETE
    strip_path: false
    
  # Attendance Service Routes
  - name: attendance-routes
    service: attendance-service
    paths:
      - /api/v2/attendance
    methods:
      - GET
      - POST
      - PUT
      - DELETE
    strip_path: false
    
  # Reimbursement Service Routes
  - name: reimbursement-routes
    service: reimbursement-service
    paths:
      - /api/v2/reimbursements
    methods:
      - GET
      - POST
      - PUT
      - DELETE
    strip_path: false
    
  # Project Service Routes
  - name: project-routes
    service: project-service
    paths:
      - /api/v2/project-attributes
    methods:
      - GET
      - POST
      - PUT
      - DELETE
    strip_path: false
    
  # Payroll Service Routes
  - name: payroll-routes
    service: payroll-service
    paths:
      - /api/v2/payroll
      - /api/v2/monthly-salary
      - /api/v2/employee-salary
      - /api/v2/payslips
      - /api/v2/payouts
    methods:
      - GET
      - POST
      - PUT
      - DELETE
    strip_path: false
    
  # Taxation Service Routes
  - name: taxation-routes
    service: taxation-service
    paths:
      - /api/v2/taxation
    methods:
      - GET
      - POST
      - PUT
      - DELETE
    strip_path: false
    
  # Reporting Service Routes
  - name: reporting-routes
    service: reporting-service
    paths:
      - /api/v2/reports
      - /api/v2/reporting
    methods:
      - GET
      - POST
      - PUT
      - DELETE
    strip_path: false

# Plugins - Cross-cutting concerns
plugins:
  # CORS Plugin
  - name: cors
    config:
      origins:
        - "http://localhost:3000"
        - "http://localhost:3001"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - HEAD
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        - Authorization
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600
      
  # Rate Limiting Plugin
  - name: rate-limiting
    config:
      minute: 1000
      hour: 10000
      policy: local
      
  # Request Size Limiting Plugin
  - name: request-size-limiting
    config:
      allowed_payload_size: 10  # 10MB
      
  # Response Transformer Plugin
  - name: response-transformer
    config:
      add:
        headers:
          - "X-Gateway-Version:1.0"
          - "X-Service-Time:{{upstream_response_time}}" 